github action don't fail when pylint convention refactor, warning occured

diff --git a/.github/workflows/pythonapp.yml b/.github/workflows/pythonapp.yml
--- a/.github/workflows/pythonapp.yml
+++ b/.github/workflows/pythonapp.yml
@@ -27,7 +27,23 @@ jobs:
     - name: Lint with pylint
       run: |
         pip install pylint
-        find . -iname '*.py' | xargs pylint 
+        for file in **/*.py; do
+          pylint "$file"
+          exit_code=$(( $? % 4 ))
+          if [[ $exit_code -ne 0 ]]; then
+            echo "an error occured in $file"
+            exit 1
+          #    else
+          #      if [[ $exit_code -eq 2 ]]; then
+          #            echo "a error occured in $file"
+          #      else
+          #        if [[ exit_code -eq 32 ]]; then
+          #            echo "a usage error occured"
+          #        fi
+          #      fi
+          fi
+        done
+        # find . -iname '*.py' | xargs pylint 
         # stop the build if there are Python syntax errors or undefined names
         #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
